//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL08PJ02.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AL08PJ02.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _10PERG1MILHAO {
            get {
                return ResourceManager.GetStream("_10PERG1MILHAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _1PERG1MIL {
            get {
                return ResourceManager.GetStream("_1PERG1MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _2PERG10MIL {
            get {
                return ResourceManager.GetStream("_2PERG10MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _3PERG20MIL {
            get {
                return ResourceManager.GetStream("_3PERG20MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _4PERG30MIL {
            get {
                return ResourceManager.GetStream("_4PERG30MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _5PERG50MIL {
            get {
                return ResourceManager.GetStream("_5PERG50MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _6PERG100MIL {
            get {
                return ResourceManager.GetStream("_6PERG100MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _7PERG200MIL {
            get {
                return ResourceManager.GetStream("_7PERG200MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _8PERG300MIL {
            get {
                return ResourceManager.GetStream("_8PERG300MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _9PERG500MIL {
            get {
                return ResourceManager.GetStream("_9PERG500MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ACERTOU {
            get {
                return ResourceManager.GetStream("ACERTOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AJUDA1 {
            get {
                return ResourceManager.GetStream("AJUDA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AJUDA2 {
            get {
                return ResourceManager.GetStream("AJUDA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ALTER {
            get {
                object obj = ResourceManager.GetObject("ALTER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BT1 {
            get {
                object obj = ResourceManager.GetObject("BT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BT1C {
            get {
                object obj = ResourceManager.GetObject("BT1C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BT1H {
            get {
                object obj = ResourceManager.GetObject("BT1H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BT2 {
            get {
                object obj = ResourceManager.GetObject("BT2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BT2H {
            get {
                object obj = ResourceManager.GetObject("BT2H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CAR0 {
            get {
                object obj = ResourceManager.GetObject("CAR0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CAR1 {
            get {
                object obj = ResourceManager.GetObject("CAR1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CAR2 {
            get {
                object obj = ResourceManager.GetObject("CAR2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CAR3 {
            get {
                object obj = ResourceManager.GetObject("CAR3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARB {
            get {
                object obj = ResourceManager.GetObject("CARB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream CARTA1 {
            get {
                return ResourceManager.GetStream("CARTA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream COMECOU {
            get {
                return ResourceManager.GetStream("COMECOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream CONFIRMOU {
            get {
                return ResourceManager.GetStream("CONFIRMOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ERROU {
            get {
                return ResourceManager.GetStream("ERROU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream GANHOU {
            get {
                return ResourceManager.GetStream("GANHOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LISTA {
            get {
                object obj = ResourceManager.GetObject("LISTA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PAN {
            get {
                object obj = ResourceManager.GetObject("PAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PAN2 {
            get {
                object obj = ResourceManager.GetObject("PAN2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PANSOM {
            get {
                object obj = ResourceManager.GetObject("PANSOM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PARAR {
            get {
                return ResourceManager.GetStream("PARAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PERGUNTA {
            get {
                return ResourceManager.GetStream("PERGUNTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PLAC {
            get {
                object obj = ResourceManager.GetObject("PLAC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PLACA1 {
            get {
                return ResourceManager.GetStream("PLACA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PLACA2 {
            get {
                return ResourceManager.GetStream("PLACA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SELECT1 {
            get {
                return ResourceManager.GetStream("SELECT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SELECT2 {
            get {
                return ResourceManager.GetStream("SELECT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SELECT3 {
            get {
                return ResourceManager.GetStream("SELECT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SELECTMUITO {
            get {
                return ResourceManager.GetStream("SELECTMUITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SETAA {
            get {
                object obj = ResourceManager.GetObject("SETAA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SETAAC {
            get {
                object obj = ResourceManager.GetObject("SETAAC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SETAAH {
            get {
                object obj = ResourceManager.GetObject("SETAAH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SHOWDOMILHAO {
            get {
                return ResourceManager.GetStream("SHOWDOMILHAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream TCHAU {
            get {
                return ResourceManager.GetStream("TCHAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TXT {
            get {
                object obj = ResourceManager.GetObject("TXT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
